version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - .:/var/www/html  # Mount the current directory to the container
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=shop_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: shop_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: