services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: swiftbuy
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
